queues:
    host: localhost
    port: 5672
    user: admin
    password: admin
    names:
        resize: resize
        upload: upload
        done: done
        failed: failed

resizer:
    side: 640
    bg-color: '#ffffff' # what colour to use for background if image is not fit new ratio
    delete-origin: false

storage:
    type: amazon-s3  # can be: amazon-s3 for Amazon S3 storage, g-drive for Google Drive, dropbox for Dropbox
    credentials:
        id: ~
        sercret: ~