queues:
    host: localhost
    port: 5672
    user: admin
    password: admin
    names:
        resize: resize
        upload: upload
        done: done
        failed: failed

resizer:
    side: 640
    bg-color: '#ffffff' # what colour to use for background if image is not fit new ratio
    delete-origin: false

storage:
    type: g-drive  # can be: amazon-s3 for Amazon S3 storage, dropbox for Dropbox, g-drive for Google Drive
    credentials:
        config-file: D:\Lightsoft\home\sandbox\24sessions-mike-1bdf850dc919.json
